# Generated by Django 4.1.dev20211231054910 on 2022-01-02 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('fotoNegocio', models.CharField(max_length=200)),
                ('fotoLogotipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cuentaFacebook', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('privilegios', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dayweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precioMensual', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datosContacto', models.CharField(max_length=200)),
                ('formaContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.contactform')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='Businesshourday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaAbre', models.DateTimeField(verbose_name='horario de apertura')),
                ('horaCierra', models.DateTimeField(verbose_name='horario de cierre')),
                ('diaSemana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.dayweek')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.business')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.heading')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client'),
        ),
        migrations.AddField(
            model_name='business',
            name='suscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.subscription'),
        ),
    ]
