# Generated by Django 4.1.dev20211231054910 on 2022-01-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='BusinessContactForm',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='direccion',
            new_name='caracteristicas',
        ),
    ]
