# Generated by Django 4.0 on 2022-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_business_fotonegocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='fotoLogotipo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
