# Generated by Django 4.0 on 2022-01-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_client_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshourday',
            name='horaAbre',
            field=models.TimeField(verbose_name='horario de apertura'),
        ),
        migrations.AlterField(
            model_name='businesshourday',
            name='horaCierra',
            field=models.TimeField(verbose_name='horario de cierre'),
        ),
    ]
