# Generated by Django 4.0 on 2022-01-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_heading_negociorubro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='negocioRubro',
        ),
        migrations.AddField(
            model_name='business',
            name='negocioRubro',
            field=models.ManyToManyField(through='polls.BusinessArea', to='polls.Heading'),
        ),
    ]
