# Generated by Django 4.0 on 2022-01-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_negociorubro_business_rubros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='Rubros',
            new_name='rubros',
        ),
    ]
