# Generated by Django 4.0 on 2022-01-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_rubros_business_rubros'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='formasContacto',
            field=models.ManyToManyField(through='polls.BusinessContactForm', to='polls.ContactForm'),
        ),
    ]
