# Generated by Django 4.0 on 2022-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_business_diassemana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshourday',
            name='horaAbre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businesshourday',
            name='horaCierra',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
