# Generated by Django 4.0 on 2022-01-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_businesshourday_horaabre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='logo',
            field=models.ImageField(default='noneyo', upload_to='images/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='business',
            name='fotoLogotipo',
            field=models.ImageField(upload_to='images/', verbose_name='Logo del Negocio'),
        ),
        migrations.AlterField(
            model_name='business',
            name='fotoNegocio',
            field=models.ImageField(upload_to='images/', verbose_name='Foto del Negocio'),
        ),
        migrations.AlterField(
            model_name='businesscontactform',
            name='datosContacto',
            field=models.CharField(help_text='para número, ingrese el codigo de area seguido del 15 y luego el numero', max_length=200),
        ),
        migrations.AlterField(
            model_name='businesshourday',
            name='horaAbre',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Abre'),
        ),
        migrations.AlterField(
            model_name='businesshourday',
            name='horaCierra',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Cierra'),
        ),
    ]
