# Generated by Django 4.0 on 2022-02-08 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_client_apellido_remove_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='fotoLogotipo',
        ),
        migrations.AlterField(
            model_name='business',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='suscripcion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.subscription'),
        ),
        migrations.AlterField(
            model_name='client',
            name='privilegios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='dayweek',
            name='dia',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
