# Generated by Django 4.0 on 2022-02-09 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_business_fotologotipo_alter_business_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cuentaFacebook',
        ),
    ]
