# Generated by Django 4.0 on 2022-02-14 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_client_cuentafacebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='precioMensual',
            field=models.FloatField(verbose_name='Precio Mensual'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de la transaccion')),
                ('installments', models.IntegerField(verbose_name='Cuotas')),
                ('payment_method_id', models.CharField(max_length=250, verbose_name='Forma de pago')),
                ('email', models.EmailField(max_length=254)),
                ('doc_number', models.CharField(max_length=250, verbose_name='Forma de pago')),
                ('mercado_pago_id', models.CharField(blank=True, db_index=True, max_length=250)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=250)),
                ('mercado_pago_status_detail', models.CharField(blank=True, max_length=250)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='polls.business')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
    ]
