# Generated by Django 4.0 on 2022-02-16 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_business_paid_alter_subscription_preciomensual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=250)),
                ('fechaUltimoPago', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Fecha Ultimo Pago')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.business')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
