# Generated by Django 4.0 on 2022-02-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_pago_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha ultimo pago'),
        ),
    ]
